--[[
	@notes: 
	-@hexadecival: handle drawlist and components more efficiently
	-@hexadecival: solve colissions
	-@hexadecival: implement rotations and scaling
	-@hexadecival: work on and finish all empty classes
	-@hexadecival: implement spritesheet system and more efficient image-related memory handling
	-@hexadecival: create raycasting algorithm
	-@hexadecival: work on editor
	-@hexadecival: create plugin system
--]]